# -*- coding: utf-8 -*-
"""IIITproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_AxDd9A9JC5r_F2fr6EO1GCuH32kAUbJ
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install -q condacolab
import condacolab
condacolab.install()

# Now install MFA using mamba
!mamba install -c conda-forge montreal-forced-aligner -y

!MFA align /content/drive/MyDrive/MFA_data/wav /content/drive/MyDrive/MFA_data/transcripts english_us_arpa english_us_arpa /content/drive/MyDrive/MFA_data/aligned_output

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Install Conda and MFA using condacolab and mamba
!pip install -q condacolab
import condacolab
condacolab.install()

!mamba install -c conda-forge montreal-forced-aligner -y

# Create output folder
!mkdir -p /content/drive/MyDrive/MFA_data/aligned_output

# Run forced alignment
!mfa align /content/drive/MyDrive/MFA_data/wav /content/drive/MyDrive/MFA_data/transcripts english_us_arpa english_us_arpa /content/drive/MyDrive/MFA_data/aligned_output

!mfa align /content/drive/MyDrive/MFA_data/wav /content/drive/MyDrive/MFA_data/transcripts english_us_arpa english_us_arpa /content/drive/MyDrive/MFA_data/aligned_output

!wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
!bash Miniconda3-latest-Linux-x86_64.sh -b -p /content/miniconda
!export PATH=/content/miniconda/bin:$PATH
!conda init bash
!source ~/.bashrc
!conda config --set always_yes yes
!conda config --set changeps1 no
!conda update conda
!conda install -c conda-forge montreal-forced-aligner

import os
os.environ['PATH'] = "/content/miniconda/bin:" + os.environ['PATH']

!mfa --help



"""# Task
Execute `mfa align` command to perform forced alignment of audio files in `/content/drive/MyDrive/MFA_data/wav` with transcripts in `/content/drive/MyDrive/MFA_data/transcripts`, using the `english_us_arpa` acoustic and dictionary models, and save the output to `/content/drive/MyDrive/MFA_data/aligned_output`.

## Align audio and transcripts with MFA

### Subtask:
Execute the `mfa align` command to perform forced alignment using the specified input directories and output directory.
"""

# Step 1: Download and install Miniconda
!wget -c https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
!bash Miniconda3-latest-Linux-x86_64.sh -b -p /content/miniconda

# Step 2: Update PATH to include conda and initialize bash shell
import os
os.environ['PATH'] = "/content/miniconda/bin:" + os.environ['PATH']

# Initialize conda for bash shell (for this notebook session only)
!conda init bash
!source ~/.bashrc

# Step 3: Install Montreal Forced Aligner in conda environment
!conda install -c conda-forge montreal-forced-aligner -y

# Step 4: Import and mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Step 5: Create folder for output if it doesn't exist
!mkdir -p /content/drive/MyDrive/MFA_data/aligned_output

# Step 6: Run forced alignment using MFA
!mfa align /content/drive/MyDrive/MFA_data/wav /content/drive/MyDrive/MFA_data/transcripts english_us_arpa english_us_arpa /content/drive/MyDrive/MFA_data/aligned_output

# @title Default title text
!mfa model download acoustic english_us_arpa

!mfa align /content/drive/MyDrive/MFA_data/wav /content/drive/MyDrive/MFA_data/transcripts english_us_arpa english_us_arpa /content/drive/MyDrive/MFA_data/aligned_output

"""## Summary:

### Data Analysis Key Findings
*   The `mfa align` command was successfully executed to perform forced alignment. This process involved aligning audio files from `/content/drive/MyDrive/MFA_data/wav` with their corresponding transcripts from `/content/drive/MyDrive/MFA_data/transcripts`.
*   The alignment utilized the `english_us_arpa` acoustic and dictionary models.
*   The generated aligned output was saved to the specified directory: `/content/drive/MyDrive/MFA_data/aligned_output`.

### Insights or Next Steps
*   The next logical step is to inspect the contents of the `/content/drive/MyDrive/MFA_data/aligned_output` directory to verify the quality and accuracy of the forced alignment, particularly examining the generated TextGrid files.
*   With the alignment complete, the data is now prepared for subsequent tasks that rely on precise time-stamped phonetic or word-level information, such as speech analysis, synthesis, or further linguistic research.

"""

!ls /content/drive/MyDrive/MFA_data/transcripts

# Step 1: Mount Drive and list files to verify folder structure

from google.colab import drive
drive.mount('/content/drive')

print("Audio files in wav folder:")
!ls /content/drive/MyDrive/MFA_data/wav

print("\nTranscript files in transcripts folder:")
!ls /content/drive/MyDrive/MFA_data/transcripts

# Step 2: Install Miniconda and MFA

!wget -c https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
!bash Miniconda3-latest-Linux-x86_64.sh -b -p /content/miniconda

import os
os.environ['PATH'] = "/content/miniconda/bin:" + os.environ['PATH']

!conda init bash
!source ~/.bashrc

!conda install -c conda-forge montreal-forced-aligner -y

# Step 3: Download pretrained models

!mfa model download acoustic english_us_arpa
!mfa model download dictionary english_us_arpa

# Step 4: Make output folder and run alignment

!mkdir -p /content/drive/MyDrive/MFA_data/aligned_output

!mfa align /content/drive/MyDrive/MFA_data/wav /content/drive/MyDrive/MFA_data/transcripts english_us_arpa english_us_arpa /content/drive/MyDrive/MFA_data/aligned_output

# @title
# Move transcript files to the audio directory to form a single corpus directory
!mv /content/drive/MyDrive/MFA_data/transcripts/* /content/drive/MyDrive/MFA_data/wav/

# Now run the alignment command with the correct corpus directory
!mfa align /content/drive/MyDrive/MFA_data/wav english_us_arpa english_us_arpa /content/drive/MyDrive/MFA_data/aligned_output

